name: "barber-shop"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: barbershop
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data:
    driver: local
